version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:5
    ports:
      - "6379:6379"

volumes:
  postgres-data: {}
